discord:
  secret: #1
  guild: #1
  channel: #1
  role: #1
  # should usually be false except for ONE thing. i dont want to deal with multi shard management so this works.
  respond-to-messages: false

  help-channel-id: 1
  info-channel-id: 2

bedrock-prefix: "." # this option will be ignored if floodgate is available.

urls:
  discord-server: 'https://google.com'
  student-union: 'https://yahoo.com'

server:
  main-hostname: 'example.org'
  bedrock-port: 19132