name: studentWhitelister

version: '1.1'
main: com.github.cinnamondev.studentWhitelister.StudentWhitelister
api-version: '1.21'
bootstrapper: com.github.cinnamondev.studentWhitelister.StudentWhitelisterBootstrap

dependencies:
  server:
    # we will use floodgate to determine if a player is a bedrock player or not.
    floodgate:
      required: false