name: studentWhitelister

version: '1.0-SNAPSHOT'
main: com.github.cinnamondev.studentWhitelister.StudentWhitelister
api-version: '1.21'
bootstrapper: com.github.cinnamondev.studentWhitelister.StudentWhitelisterBootstrap
